dataset:
  _target_: afa4cate.datasets.synthetic.SyntheticCATEDataset

  n_samples: 10000        # Number of samples
  setup_pi: overlap_violation   # 'random' for random treatment assignment
  rho_TE: 0.7             # probability of non-zero treatment effect
  seed: ${random_seed}    # Random seed
  mode: 'mu'              # 'mu' for potential outcome prediction, 'pi' for propensity score prediction
  split: null             # 'train' for training set, 'test' for test set, 'valid' for validation set

num_ones: 3
dataset_name: acic2016
