random_seed: 1
experiment_name: test_run
wandb_log: False
job_dir: null
experiment_dir: null
acquisition_metric: 'random'
device: "cpu"

tune_cate_model: True
tune:
  max_samples: 20
  time_budget_s: 600

acquisition:
  subsample: "random"
  n_test_samples: 30
  n_j_samples: 20
  n_cond_samples: 200
  n_posterior_samples: 50
  track_predictive_acquisition: True
  threshold_variable: "sTE"
  percentile_var_threshold: 0.85
  proportion_above_threshold: 0.95
  alpha: 1.0


defaults:
- cate_model: deep_kernel_gp
- dataset: acic2016
- gs_model: gaussian_gsm
