random_seed: 1
experiment_name: fixed_acic2016
wandb_log: False
save_to_csv: False
job_dir: null
experiment_dir: null
acquisition_metric: 'random'
device: "cuda:0"

rho_cov: 'acic2016'
d: 21

tune_cate_model: True
tune:
  max_samples: 100
  time_budget_s: 1800

pi_model:
  seed: ${random_seed}
  dim_hidden: 128
  dim_output: 1
  depth: 3
  negative_slope: -100.0
  spectral_norm: 3.0
  dropout_rate: 0.5
  learning_rate: 0.001
  batch_size: 1000
  epochs: 500
  patience: 50
  device: ${device}

var_model:
  seed: ${random_seed}
  dim_hidden: 128
  dim_output: 1
  depth: 3
  negative_slope: 1.0
  spectral_norm: 3.0
  dropout_rate: 0.5
  learning_rate: 0.001
  batch_size: 1000
  epochs: 500
  patience: 50
  device: ${device}

acquisition:
  subsample: "random"
  n_test_samples: 30
  n_j_samples: 20
  n_cond_samples: 200
  n_posterior_samples: 50
  track_predictive_acquisition: True
  threshold_variable: "sTE"
  percentile_var_threshold: 0.85
  proportion_above_threshold: 0.95
  alpha: 1.0


defaults:
- cate_model: deep_kernel_gp
- dataset: ihdp
- gs_model: gaussian_gsm
